FROM python:3.9-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt
RUN chmod +x /app/wait-for-it.sh

CMD ["/app/wait-for-it.sh", "postgres:5432", "--", "/app/wait-for-it.sh", "kafka:9092", "--", "python", "main.py"]


